import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import Link from "next/link";
import { getUserFromCookie } from "../utils/cookie";
import { logOut }from "../actions/profileController"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getUserFromCookie();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className="navbar">
          <Link className="brand" href="/">Recipio</Link>
          <div className="links">

            {user ? (
              <>
              <Link href="/my-job-offers">My Job Offers</Link>
                <Link href="/profile">Profile</Link>
                <form action={logOut} >
                  <button className="">
                    Sign-Out
                  </button>
                </form>
              </>
            ) :
              <Link href="/log-in">Log-in</Link>
            }
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
