import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className="navbar">
          <div className="brand">Recipio</div>
          <div className="links">
            {/* <a href="#about">About</a> */}
            <Link href="/recipies">Recipies</Link>
            <Link href="/profile">Profile</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
